### ISSUE TITLE
help want

### ISSUE THREAD

**Issue by Linsuns** [chenfeiyi/AutoExCali#1]
Hello, I recently read your paper, but I couldn't find the relevant code mentioned in the paper. Could you please provide it?

**Comment by chenfeiyi** [comment]
Sorry for the late reply.  We didn't upload the code for it's too messy, if you want to calibrate the extrinsics between camera and lidar. I recommend you to visit this repo https://github.com/HKUSTGZ-IADC/LCECalib. The code in the recommended repo is part from this work. For the code in this work (AutoExcali), I hope I got more time to sort up the code. Emmmm, say two weeks. If I finished, I will let you know.

**Comment by chenfeiyi** [comment]
Hi, Linsuns. I hope the code uploaded today can solve your issue.

**Comment by Linsuns** [comment]
That's great, thank you very much.

**Comment by chenfeiyi** [comment]
You are welcome.
